[MDA] = LAYOUT_ergodox(

	KC_TRNS,  KC_PWR,  KC_APP, KC_WBAK, KC_MPRV, KC_VOLU, KC_MUTE,
	KC_TRNS, KC_SLEP, KC_WFAV, KC_WFWD, KC_MNXT, KC_VOLD, KC_TRNS,
	KC_TRNS, KC_WAKE, KC_WSTP, KC_WHOM, KC_MPLY, KC_BRIU,         
	KC_TRNS, KC_CALC, KC_MAIL, KC_WSCH, KC_MRWD, KC_BRID, KC_TRNS,
	KC_TRNS, KC_MYCM, KC_MSEL, KC_WREF, KC_MFFD,                  
	                                             KC_TRNS, KC_TRNS,
	                                                      KC_TRNS,
	                                    KC_TRNS, KC_TRNS, KC_TRNS,

	KC_MUTE, KC_VOLU, KC_MPRV, KC_WBAK, KC_APP,  KC_PWR,  KC_TRNS,
	KC_TRNS, KC_VOLD, KC_MNXT, KC_WFWD, KC_WFAV, KC_SLEP, KC_TRNS,
	         KC_BRIU, KC_MPLY, KC_WHOM, KC_WSTP, KC_WAKE, KC_TRNS,
	KC_TRNS, KC_BRID, KC_MRWD, KC_WSCH, KC_MAIL, KC_CALC, KC_TRNS,
	                  KC_MFFD, KC_WREF, KC_MSEL, KC_MYCM, KC_TRNS,
	KC_TRNS, KC_TRNS,
	KC_TRNS,
	KC_TRNS, KC_TRNS, KC_TRNS
),

